force_cast: warning
force_try: warning
excluded:
    - Package.swift
disabled_rules:
    - file_header
analyzer_rules:
    - unused_import
    - weak_delegate
    - empty_string
    - attributes
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - comma_inheritance
    - explicit_self
    - file_header
    - let_var_whitespace
    - literal_expression_end_indentation
    - modifier_order
    - number_separator
    - operator_usage_whitespace
    - optional_enum_case_matching
    - prefer_self_in_static_references
    - prefer_self_type_over_type_of_self
    - prefixed_toplevel_constant
    - self_binding
    - single_test_class
    - sorted_imports
    - trailing_closure
    - unneeded_parentheses_in_closure_argument
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_between_cases
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - anonymous_argument_in_multiline_closure
    - convenience_type
    - extension_access_modifier
    - fallthrough
    - function_default_parameter_at_end
    - implicitly_unwrapped_optional
    - joined_default_parameter
    - legacy_multiple
    - legacy_objc_type
    - nimble_operator
    - no_extension_access_modifier
    - no_grouping_extension
    - object_literal
    - pattern_matching_keywords
    - prefer_nimble
    - prefer_zero_over_explicit_init
    - redundant_nil_coalescing
    - return_value_from_void_function
    - shorthand_optional_binding
    - static_operator
    - strict_fileprivate
    - toggle_bool
    - accessibility_label_for_image
    - accessibility_trait_for_button
    - array_init
    - balanced_xctest_lifecycle
    - capture_variable
    - closure_body_length
    - conditional_returns_on_newline
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - direct_return
    - discarded_notification_center_observer
    - discouraged_assert
    - discouraged_none_name
    - discouraged_object_literal
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - empty_collection_literal
    - empty_count
    - empty_xctest_method
    - enum_case_associated_values_count
    - expiring_todo
    - explicit_enum_raw_value
    - explicit_init
    - file_name_no_space
    - file_types_order
    - first_where
    - flatmap_over_map_reduce
    - ibinspectable_in_extension
    - identical_operands
    - implicit_return
    - indentation_width
    - last_where
    - local_doc_comment
    - lower_acl_than_parent
    - multiline_arguments
    - non_overridable_class_declaration
    - nslocalizedstring_key
    - nslocalizedstring_require_bundle
    - overridden_super_call
    - override_in_extension
    - period_spacing
    - private_action
    - private_outlet
    - private_subject
    - private_swiftui_state
    - prohibited_interface_builder
    - prohibited_super_call
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    - raw_value_for_camel_cased_codable_enum
    - reduce_into
    - redundant_self_in_closure
    - redundant_type_annotation
    - required_enum_case
    - sorted_enum_cases
    - sorted_first_last
    - strong_iboutlet
    - superfluous_else
    - switch_case_on_newline
    - test_case_accessibility
    - type_contents_order
    - typesafe_array_init
    - unavailable_function
    - unhandled_throwing_task
    - unowned_variable_capture
    - untyped_error_in_catch
    - unused_declaration
    - xct_specific_matcher
    - yoda_condition
custom_rules:
    print_using:
        regex: 'print'
        message: "Print decrease performance of the app"
    foundation_using:
        regex: 'import Foundation'
        message: "Do you really need for Foundation ???"
